# 05 — Data Cleaning & Preparation

Turns a raw extract into an analysis-ready table, and logs every change so the
cleaning is auditable. Run it **before** EDA (01) and any modeling notebook.

**Structure**
1. Setup → 2. INPUT (edit one cell) → 3. Before-snapshot
4. Cleaning steps: column names → text/number/date types → sentinels → category standardization → duplicates → missing values → outlier capping
5. **OUTPUT**: `outputs/cleaned_data.csv` + `outputs/cleaning_log.csv`

Each cleaning step is its own cell — delete the ones you don't need.

In [1]:
# ============================================================
# SETUP — run this cell first (no edits needed)
# ============================================================
# If any import fails, run in a notebook cell:
#   %pip install pandas numpy matplotlib seaborn scikit-learn sqlalchemy joblib openpyxl
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# All files this notebook produces are saved here:
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)
print("Setup complete. Outputs will be saved to:", OUTPUT_DIR)

Setup complete. Outputs will be saved to: outputs

In [2]:
# ============================================================
# SAMPLE DATA GENERATOR (used only when DATA_SOURCE = "sample")
# ============================================================
# Creates a synthetic consumer-lending dataset so every cell below runs
# end-to-end even before you plug in your own data. Just run this cell.
def make_sample_lending_data(n=5000, seed=42):
    rng = np.random.default_rng(seed)
    fico = rng.normal(690, 55, n).clip(500, 850).round()
    dti = rng.normal(28, 10, n).clip(1, 65).round(1)
    loan_amount = rng.lognormal(9.4, 0.5, n).clip(1000, 50000).round(-2)
    income = rng.lognormal(11.1, 0.45, n).clip(15000, 400000).round(-2)
    utilization = rng.beta(2, 3, n).round(3) * 100
    tenure_months = rng.integers(0, 240, n)
    grade = rng.choice(list("ABCDE"), n, p=[0.25, 0.30, 0.25, 0.13, 0.07])
    purpose = rng.choice(["debt_consolidation", "credit_card", "home_improvement",
                          "auto", "medical", "other"], n,
                         p=[0.38, 0.22, 0.13, 0.12, 0.06, 0.09])
    state = rng.choice(["CA", "TX", "NY", "FL", "IL", "PA", "OH", "GA"], n)
    grade_rate = pd.Series(grade).map({"A": 7.5, "B": 10.5, "C": 13.5, "D": 17.0, "E": 21.0}).values
    interest_rate = (grade_rate - 0.010 * (fico - 690) + 0.02 * (dti - 28)
                     + rng.normal(0, 0.8, n)).clip(5, 30).round(2)
    origination_date = (pd.Timestamp("2023-01-01")
                        + pd.to_timedelta(rng.integers(0, 36, n) * 30, unit="D")).normalize()
    logit = (-4.2
             - 0.012 * (fico - 690)
             + 0.045 * (dti - 28)
             + 0.018 * (utilization - 40)
             + 0.35 * np.isin(grade, ["D", "E"]).astype(float)
             + 0.20 * (purpose == "debt_consolidation").astype(float))
    p_default = 1 / (1 + np.exp(-logit))
    default_flag = rng.binomial(1, p_default)
    df = pd.DataFrame({
        "loan_id": np.arange(1, n + 1),
        "origination_date": origination_date,
        "fico_score": fico, "dti": dti, "loan_amount": loan_amount,
        "annual_income": income, "revolving_utilization": utilization,
        "employment_tenure_months": tenure_months, "grade": grade,
        "loan_purpose": purpose, "state": state,
        "interest_rate": interest_rate, "default_flag": default_flag,
    })
    for col, frac in [("dti", 0.03), ("annual_income", 0.05), ("employment_tenure_months", 0.02)]:
        df.loc[df.sample(frac=frac, random_state=seed).index, col] = np.nan
    return df

print("Sample data generator defined.")

Sample data generator defined.

In [3]:
# ============================================================
# MESSY SAMPLE DATA (used only when DATA_SOURCE = "sample")
# ============================================================
# Takes the clean synthetic lending data and injects the messes you
# meet in real extracts: duplicate rows, inconsistent category text,
# sentinel values, currency-formatted numbers, and mixed date formats.
def make_messy_lending_data(n=5000, seed=42):
    rng = np.random.default_rng(seed)
    df = make_sample_lending_data(n=n, seed=seed)

    # Numbers arriving as text: "$12,300.00"
    df["loan_amount"] = df["loan_amount"].map(lambda v: f"${v:,.2f}")

    # Dates arriving as inconsistent strings
    fmts = ["%Y-%m-%d", "%m/%d/%Y", "%d-%b-%Y"]
    df["origination_date"] = [
        d.strftime(fmts[i % 3]) for i, d in enumerate(df["origination_date"])
    ]

    # Inconsistent category text (case + whitespace)
    idx = df.sample(frac=0.30, random_state=seed).index
    df.loc[idx, "loan_purpose"] = df.loc[idx, "loan_purpose"].str.upper().str.replace("_", " ")
    idx2 = df.sample(frac=0.10, random_state=seed + 1).index
    df.loc[idx2, "loan_purpose"] = " " + df.loc[idx2, "loan_purpose"] + "  "

    # Sentinel value instead of NaN
    idx3 = df.sample(frac=0.04, random_state=seed + 2).index
    df.loc[idx3, "annual_income"] = -999

    # Duplicate rows
    dupes = df.sample(frac=0.03, random_state=seed + 3)
    df = pd.concat([df, dupes], ignore_index=True)

    # Ugly column names
    return df.rename(columns={"fico_score": "FICO Score", "dti": "DTI (%)"})

print("Messy sample data generator defined.")

Messy sample data generator defined.

## INPUT — point this notebook at your data

**This is the only cell you must edit.** Set `DATA_SOURCE` to one of four options:

| `DATA_SOURCE` | What to edit | Notes |
|---|---|---|
| `"csv"` | `CSV_PATH` | Put your file in the `data/` folder next to this notebook, or use a full path |
| `"excel"` | `EXCEL_PATH`, `EXCEL_SHEET` | Needs `openpyxl`. `EXCEL_SHEET` can be a name (`"Sheet1"`) or index (`0`) |
| `"database"` | `DB_CONNECTION_STRING`, `DB_QUERY` | Uses SQLAlchemy — connection string examples are in the cell |
| `"sample"` | nothing | Generates a synthetic lending dataset so you can test-drive the notebook immediately |

After running the cell, your data lives in the DataFrame **`df`** — everything downstream reads from it.

In [4]:
# ============================================================
# INPUT — EDIT THIS CELL, then run it
# ============================================================
DATA_SOURCE = "sample"          # <-- "csv" | "excel" | "database" | "sample"

# --- Option A: CSV file ---
CSV_PATH = "data/my_data.csv"   # <-- path to your CSV

# --- Option B: Excel file ---
EXCEL_PATH = "data/my_data.xlsx"
EXCEL_SHEET = 0                 # sheet name ("Sheet1") or index (0)

# --- Option C: Database (via SQLAlchemy) ---
# Install the driver for your database first (run once in a cell):
#   SQLite      : built-in, nothing to install
#   PostgreSQL  : %pip install psycopg2-binary
#   MySQL       : %pip install pymysql
#   SQL Server  : %pip install pyodbc
#
# Connection string examples:
#   "sqlite:///data/my_database.db"
#   "postgresql+psycopg2://username:password@localhost:5432/mydb"
#   "mysql+pymysql://username:password@localhost:3306/mydb"
#   "mssql+pyodbc://username:password@server/mydb?driver=ODBC+Driver+18+for+SQL+Server"
DB_CONNECTION_STRING = "sqlite:///data/my_database.db"
DB_QUERY = "SELECT * FROM loans"   # <-- any SQL that returns the rows you want

# ------------------------------------------------------------
# Loading logic — no edits needed below this line
# ------------------------------------------------------------
if DATA_SOURCE == "csv":
    df = pd.read_csv(CSV_PATH)
elif DATA_SOURCE == "excel":
    df = pd.read_excel(EXCEL_PATH, sheet_name=EXCEL_SHEET)
elif DATA_SOURCE == "database":
    from sqlalchemy import create_engine
    engine = create_engine(DB_CONNECTION_STRING)
    df = pd.read_sql(DB_QUERY, engine)
elif DATA_SOURCE == "sample":
    df = make_messy_lending_data()
else:
    raise ValueError(f"Unknown DATA_SOURCE: {DATA_SOURCE!r}")

print(f"Loaded {df.shape[0]:,} rows x {df.shape[1]} columns from source: {DATA_SOURCE}")
df.head()

Loaded 5,150 rows x 13 columns from source: sample

,loan_id,origination_date,FICO Score,DTI (%),loan_amount,annual_income,revolving_utilization,employment_tenure_months,grade,loan_purpose,state,interest_rate,default_flag
0,1,2025-11-16,707.0000,25.4000,"$13,200.00","100,500.0000",41.2000,98.0000,C,medical,CA,12.3900,0
1,2,02/25/2024,633.0000,25.0000,"$19,000.00","102,000.0000",69.9000,194.0000,A,home_improvement,TX,6.3900,0
2,3,20-Jan-2025,731.0000,21.0000,"$5,800.00","92,700.0000",53.4000,147.0000,B,debt_consolidation,NY,9.9000,0
3,4,2023-07-30,742.0000,32.3000,"$10,500.00","80,700.0000",64.5000,17.0000,C,credit_card,CA,13.8200,0
4,5,12/21/2024,583.0000,30.3000,"$18,300.00","79,700.0000",36.5000,89.0000,A,debt_consolidation,GA,9.3800,0

In [5]:
# ============================================================
# 3. BEFORE snapshot — we log every step against this baseline
# ============================================================
cleaning_log = []
def log_step(step, detail):
    cleaning_log.append({"step": step, "detail": detail,
                         "rows": len(df), "columns": df.shape[1]})
    print(f"[{step}] {detail}  ->  {len(df):,} rows x {df.shape[1]} cols")

print(f"BEFORE: {df.shape[0]:,} rows x {df.shape[1]} cols")
print(f"Exact duplicates: {df.duplicated().sum():,}")
df.dtypes.to_frame("dtype")

BEFORE: 5,150 rows x 13 cols
Exact duplicates: 150

                            dtype
loan_id                     int64
origination_date           object
FICO Score                float64
DTI (%)                   float64
loan_amount                object
annual_income             float64
revolving_utilization     float64
employment_tenure_months  float64
grade                      object
loan_purpose               object
state                      object
interest_rate             float64
default_flag                int64

In [6]:
# ============================================================
# 4.1 Standardize column names -> snake_case
# ============================================================
import re
def to_snake(name):
    name = re.sub(r"[^\w\s]", "", str(name)).strip()
    name = re.sub(r"\s+", "_", name)
    return name.lower()

before = list(df.columns)
df.columns = [to_snake(c) for c in df.columns]
renamed = {b: a for b, a in zip(before, df.columns) if b != a}
log_step("column_names", f"renamed {len(renamed)}: {renamed}")

[column_names] renamed 2: {'FICO Score': 'fico_score', 'DTI (%)': 'dti'}  ->  5,150 rows x 13 cols

In [7]:
# ============================================================
# 4.2 Fix types — numbers stored as text, and date columns
# ============================================================
# EDIT these lists for your data:
NUMERIC_TEXT_COLS = ["loan_amount"]        # numbers arriving as "$1,234.00" etc.
DATE_COLS = ["origination_date"]           # date columns to parse

for c in NUMERIC_TEXT_COLS:
    if c in df.columns and df[c].dtype == object:
        df[c] = pd.to_numeric(df[c].astype(str).str.replace(r"[$,\s]", "", regex=True),
                              errors="coerce")
        log_step("numeric_cast", f"{c}: text -> float ({df[c].isna().sum()} unparseable -> NaN)")

for c in DATE_COLS:
    if c in df.columns:
        df[c] = pd.to_datetime(df[c], errors="coerce", format="mixed")
        log_step("date_parse", f"{c}: parsed to datetime ({df[c].isna().sum()} unparseable -> NaN)")

[numeric_cast] loan_amount: text -> float (0 unparseable -> NaN)  ->  5,150 rows x 13 cols
[date_parse] origination_date: parsed to datetime (0 unparseable -> NaN)  ->  5,150 rows x 13 cols

In [8]:
# ============================================================
# 4.3 Replace sentinel values with proper NaN
# ============================================================
# EDIT: sentinel codes your source systems use for "unknown"
SENTINELS = [-999, -9999, 9999999, "N/A", "NULL", "missing", "unknown", ""]

n_before = int(df.isna().sum().sum())
df = df.replace(SENTINELS, np.nan)
log_step("sentinels", f"converted {int(df.isna().sum().sum()) - n_before:,} sentinel values to NaN")

[sentinels] converted 204 sentinel values to NaN  ->  5,150 rows x 13 cols

In [9]:
# ============================================================
# 4.4 Standardize category text (trim, lowercase, unify separators)
# ============================================================
text_cols = df.select_dtypes(include="object").columns
for c in text_cols:
    n_levels_before = df[c].nunique()
    df[c] = (df[c].astype(str).str.strip().str.lower()
                  .str.replace(r"\s+", "_", regex=True)
                  .replace({"nan": np.nan}))
    if df[c].nunique() != n_levels_before:
        log_step("text_standardize", f"{c}: {n_levels_before} -> {df[c].nunique()} distinct values")

[text_standardize] loan_purpose: 24 -> 6 distinct values  ->  5,150 rows x 13 cols

In [10]:
# ============================================================
# 4.5 Remove duplicates
# ============================================================
# Exact duplicates are always safe to drop. If you have a business key
# (e.g. loan_id), also dedupe on it, keeping the last record.
KEY_COLS = ["loan_id"]   # <-- your business key, or [] to skip

n0 = len(df)
df = df.drop_duplicates()
log_step("dedupe_exact", f"dropped {n0 - len(df):,} exact duplicate rows")

if KEY_COLS and all(c in df.columns for c in KEY_COLS):
    n0 = len(df)
    df = df.sort_values(KEY_COLS).drop_duplicates(subset=KEY_COLS, keep="last")
    log_step("dedupe_key", f"dropped {n0 - len(df):,} rows duplicated on {KEY_COLS}")

[dedupe_exact] dropped 150 exact duplicate rows  ->  5,000 rows x 13 cols
[dedupe_key] dropped 0 rows duplicated on ['loan_id']  ->  5,000 rows x 13 cols

In [11]:
# ============================================================
# 4.6 Missing values — choose a strategy per column
# ============================================================
# Three options per column: "drop_rows", "median"/"mode" impute, or
# "flag_and_median" (adds <col>_missing indicator, then imputes —
# best when missingness itself is informative).
MISSING_STRATEGY = {
    "dti": "flag_and_median",
    "annual_income": "flag_and_median",
    "employment_tenure_months": "median",
}

for c, strat in MISSING_STRATEGY.items():
    if c not in df.columns or df[c].isna().sum() == 0:
        continue
    n_miss = int(df[c].isna().sum())
    if strat == "drop_rows":
        df = df.dropna(subset=[c])
        log_step("missing", f"{c}: dropped {n_miss:,} rows")
    elif strat == "median":
        df[c] = df[c].fillna(df[c].median())
        log_step("missing", f"{c}: {n_miss:,} imputed with median")
    elif strat == "mode":
        df[c] = df[c].fillna(df[c].mode().iloc[0])
        log_step("missing", f"{c}: {n_miss:,} imputed with mode")
    elif strat == "flag_and_median":
        df[c + "_missing"] = df[c].isna().astype(int)
        df[c] = df[c].fillna(df[c].median())
        log_step("missing", f"{c}: {n_miss:,} imputed + indicator column added")

[missing] dti: 150 imputed + indicator column added  ->  5,000 rows x 14 cols
[missing] annual_income: 440 imputed + indicator column added  ->  5,000 rows x 15 cols
[missing] employment_tenure_months: 100 imputed with median  ->  5,000 rows x 15 cols

In [12]:
# ============================================================
# 4.7 Outlier treatment — cap (winsorize) at percentiles
# ============================================================
# Capping keeps the row but limits extreme values' leverage.
# EDIT: columns to cap and the percentile bounds.
CAP_COLS = ["annual_income", "loan_amount", "revolving_utilization"]
LOWER_P, UPPER_P = 0.01, 0.99

for c in CAP_COLS:
    if c not in df.columns:
        continue
    lo, hi = df[c].quantile([LOWER_P, UPPER_P])
    n_capped = int(((df[c] < lo) | (df[c] > hi)).sum())
    df[c] = df[c].clip(lo, hi)
    log_step("outlier_cap", f"{c}: {n_capped:,} values capped to [{lo:,.0f}, {hi:,.0f}]")

[outlier_cap] annual_income: 98 values capped to [23,800, 183,300]  ->  5,000 rows x 15 cols
[outlier_cap] loan_amount: 97 values capped to [3,900, 38,700]  ->  5,000 rows x 15 cols
[outlier_cap] revolving_utilization: 99 values capped to [4, 87]  ->  5,000 rows x 15 cols

In [13]:
# ============================================================
# 4.8 Consolidate rare category levels into "other"
# ============================================================
MIN_LEVEL_SHARE = 0.01   # levels below 1% of rows get grouped

for c in df.select_dtypes(include="object").columns:
    shares = df[c].value_counts(normalize=True)
    rare = shares[shares < MIN_LEVEL_SHARE].index
    if len(rare) > 0:
        df[c] = df[c].replace(dict.fromkeys(rare, "other"))
        log_step("rare_levels", f"{c}: {len(rare)} rare levels -> 'other'")

## 5. OUTPUT — cleaned data + audit log

- `outputs/cleaned_data.csv` — feed this into EDA (01) and the modeling notebooks
- `outputs/cleaning_log.csv` — every step, what it changed, and the row/column count after it

In [14]:
# ============================================================
# 5. OUTPUT
# ============================================================
df.to_csv(OUTPUT_DIR / "cleaned_data.csv", index=False)
log_df = pd.DataFrame(cleaning_log)
log_df.to_csv(OUTPUT_DIR / "cleaning_log.csv", index=False)

print(f"AFTER: {df.shape[0]:,} rows x {df.shape[1]} cols")
print("Saved: outputs/cleaned_data.csv, outputs/cleaning_log.csv")
log_df

AFTER: 5,000 rows x 15 cols
Saved: outputs/cleaned_data.csv, outputs/cleaning_log.csv

,step,detail,rows,columns
0,column_names,"renamed 2: {'FICO Score': 'fico_score', 'DTI (...",5150,13
1,numeric_cast,loan_amount: text -> float (0 unparseable -> NaN),5150,13
2,date_parse,origination_date: parsed to datetime (0 unpars...,5150,13
3,sentinels,converted 204 sentinel values to NaN,5150,13
4,text_standardize,loan_purpose: 24 -> 6 distinct values,5150,13
5,dedupe_exact,dropped 150 exact duplicate rows,5000,13
6,dedupe_key,dropped 0 rows duplicated on ['loan_id'],5000,13
7,missing,dti: 150 imputed + indicator column added,5000,14
8,missing,annual_income: 440 imputed + indicator column ...,5000,15
9,missing,employment_tenure_months: 100 imputed with median,5000,15
10,outlier_cap,"annual_income: 98 values capped to [23,800, 18...",5000,15
11,outlier_cap,"loan_amount: 97 values capped to [3,900, 38,700]",5000,15
12,outlier_cap,"revolving_utilization: 99 values capped to [4,...",5000,15